name			  "spidermonkey"
maintainer        "Rob Porter"
maintainer_email  "rob@weeverapps.com"
license           "Apache 2.0"
description       "Sets up spidermonkey"
version           "0.2"
long_description  "Sets up spidermonkey"
